var dummyData = [
  {
    "id": 1,
    "title": "End the Ocean",
    "author": "Andreas Blomqvist",
    "image": "https://i.harperapps.com/covers/9780062951366/x300.jpg",
    "description": "",
    "typeOfTrade": "",
    "price": "699",
    "delivery": "",
  },
  {
    "id": 2,
    "title": "Hijas Sur",
    "author": "Jenny Nilsson",
    "image": "https://i.harperapps.com/covers/9788491393900/x300.jpg",
    "description": "",
    "typeOfTrade": "",
    "price": "575",
    "delivery": "",
  },
  {
    "id": 3,
    "title": "Corporate: Gunslinger Potato Corporate",
    "author": "Ben",
    "image": "https://i.harperapps.com/covers/9780062897688/x300.jpg",
    "description": "",
    "typeOfTrade": "",
    "price": "299",
    "delivery": "",
  },
  {
    "id": 4,
    "title": "Chaos reigning",
    "author": "Jonte",
    "image": "https://i.harperapps.com/covers/9780062802439/x300.jpg",
    "description": "",
    "typeOfTrade": "",
    "price": "300",
    "delivery": "",
  },
  {
    "id": 5,
    "title": "Polaris rising",
    "author": "Alex",
    "image": "https://i.harperapps.com/covers/9780062802408/x300.jpg",
    "description": "",
    "typeOfTrade": "",
    "price": "299",
    "delivery": "",
  },
  {
    "id": 6,
    "title": "Aurora blazing",
    "author": "Ben",
    "image": "https://i.harperapps.com/covers/9780062802460/x300.jpg",
    "description": "",
    "typeOfTrade": "",
    "price": "175",
    "delivery": "",
  }
];
